name: polcompballbot
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  drift_dev: ^2.4.1
  build_runner: ^2.3.3
  build_web_compilers: ^3.2.7
dependencies:
  dotenv: ^4.0.1
  drift: ^2.4.2
  nyxx: ^4.4.1
  nyxx_interactions: ^4.5.0
  path: ^1.8.3
  enum_flag: ^1.0.1
  http: ^0.13.5
  web_scraper: ^0.1.4
